-- 04_roles_perm.sql
-- TABLA ROLES
CREATE TABLE IF NOT EXISTS roles (
  role_id INT AUTO_INCREMENT PRIMARY KEY,
  role_name VARCHAR(80) NOT NULL UNIQUE,
  role_desc VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- TABLA PERMISSIONS (funciones)
CREATE TABLE IF NOT EXISTS permissions (
  perm_id INT AUTO_INCREMENT PRIMARY KEY,
  perm_key VARCHAR(100) NOT NULL UNIQUE, -- e.g. "users.create"
  perm_desc VARCHAR(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- RELACION ROLE <-> PERMISSION
CREATE TABLE IF NOT EXISTS role_permissions (
  rp_id INT AUTO_INCREMENT PRIMARY KEY,
  role_id INT NOT NULL,
  perm_id INT NOT NULL,
  UNIQUE KEY (role_id, perm_id),
  FOREIGN KEY (role_id) REFERENCES roles(role_id) ON DELETE CASCADE,
  FOREIGN KEY (perm_id) REFERENCES permissions(perm_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- RELACION USER <-> ROLE
CREATE TABLE IF NOT EXISTS user_roles (
  ur_id INT AUTO_INCREMENT PRIMARY KEY,
  usercod BIGINT NOT NULL, -- coincide con tu tabla `usuario.usercod`
  role_id INT NOT NULL,
  UNIQUE KEY (usercod, role_id),
  FOREIGN KEY (usercod) REFERENCES usuario(usercod) ON DELETE CASCADE,
  FOREIGN KEY (role_id) REFERENCES roles(role_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
